name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm destruction of all resources'
        required: true
        type: string

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  TF_VERSION: '1.3.0'

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment:
      name: production
    
    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "destroy" ]; then
            echo "❌ Confirmation failed. You must type 'destroy' to proceed."
            exit 1
          fi
          echo "✅ Confirmation validated"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials for Spaces
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.SPACES_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          EOF

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan Destroy
        id: plan
        run: |
          terraform plan -destroy -no-color -out=tfdestroy \
            -var="do_token=${{ secrets.DO_TOKEN }}" \
            -var="ssh_key_id=${{ secrets.SSH_KEY_ID }}" \
            -var="region=${{ vars.TF_VAR_REGION || 'nyc3' }}" \
            -var="droplet_size=${{ vars.TF_VAR_DROPLET_SIZE || 's-1vcpu-1gb' }}" \
            -var="droplet_image=${{ vars.TF_VAR_DROPLET_IMAGE || 'ubuntu-24-04-x64' }}" \
            -var="droplet_name=${{ vars.TF_VAR_DROPLET_NAME || 'portafolio-droplet' }}"

      - name: Show Destroy Plan
        run: |
          echo "### ⚠️ Resources to be DESTROYED:"
          terraform show tfdestroy

      - name: Terraform Destroy
        id: destroy
        run: terraform apply -auto-approve tfdestroy

      - name: Create Summary
        if: always()
        run: |
          echo "## Terraform Destroy Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.destroy.outcome }}" == "success" ]; then
            echo "### ✅ Infrastructure destroyed successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "All resources have been destroyed from DigitalOcean." >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Destroy failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Check the logs above for error details." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
